import { test,expect,type Page,type APIRequestContext } from '@playwright/test';
import { readFileSync,mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { validateContent, type Content } from '../../src/shared/content';
import type { Snapshot } from '../../src/shared/protocol';
const readState=(page:Page)=>page.evaluate(()=>((window as any).eter.state as Snapshot));
const defaults=validateContent(JSON.parse(readFileSync(new URL('../../src/content/default.json',import.meta.url),'utf8')));
async function ready(page:Page){await page.goto('/');await page.waitForFunction(()=>!!(window as any).eter?.state,undefined,{timeout:60000});await expect(page.locator('#connection')).toBeHidden();}
async function authorize(request:APIRequestContext){const token=readFileSync(join(process.env.ETER_BROWSER_DATA!,'admin-token.txt'),'utf8').trim();expect((await request.post('/api/admin/login',{data:{token}})).ok()).toBeTruthy();}
async function config(request:APIRequestContext,mutate?:(c:Content)=>void){const current=await(await request.get('/api/admin/content')).json();const content=structuredClone(defaults) as Content;mutate?.(content);const response=await request.put('/api/admin/content',{data:{content,revision:current.revision}});expect(response.ok(),await response.text()).toBeTruthy();}
async function clickWorld(page:Page,x:number,z:number,y=0,button:'left'|'right'='left'){
  const point=await page.evaluate(({x,y,z})=>(window as any).eter.scene.project(x,y,z),{x,y,z});expect(point.visible).toBeTruthy();expect(point.y).toBeLessThan(795);await page.mouse.click(point.x,point.y,{button});
}
async function move(page:Page,x:number,z:number){await clickWorld(page,x,z);await page.waitForFunction(({x,z})=>{const p=(window as any).eter.state.me;return Math.hypot(p.x-x,p.z-z)<0.25;},{x,z},{timeout:15000});}

test('production client: Aurelia → shops → movement → attacks/skills → loot → inventory → stats → repair → account persistence',async({page,request,browser})=>{
  test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  expect((await request.get('/api/admin/content')).status()).toBe(401);await authorize(request);await config(request,c=>{c.balance.xpBase=16;for(const t of c.dropTables)for(const e of t.entries)e.chance=1;});
  await ready(page);mkdirSync('docs/evidence',{recursive:true});await page.screenshot({path:'docs/evidence/aurelia.png'});
  const initial=await readState(page);expect(initial.me.equipment.weapon?.item).toBe('ironblade');expect(initial.monsters).toHaveLength(9);expect(initial.me.hp).toBe(110);
  await page.locator('.world-label.npc').filter({hasText:'Lyra'}).click();await page.waitForFunction(()=>(window as any).eter.state.me.npc==='lyra');await page.locator('[data-buy="health"]').click();await page.waitForFunction(()=>(window as any).eter.state.me.crowns===88);await page.keyboard.press('q');await page.waitForFunction(()=>(window as any).eter.state.me.inventory.filter((i:any)=>i.item==='health').length===4);
  await page.keyboard.press('Escape');await page.locator('.world-label.npc').filter({hasText:'Brom'}).click();await page.waitForFunction(()=>(window as any).eter.state.me.npc==='brom');await page.locator('[data-buy="ironblade"]').click();await page.waitForFunction(()=>(window as any).eter.state.me.crowns===23);await page.keyboard.press('Escape');
  await page.keyboard.press('i');const bagState=await readState(page),sword=bagState.me.inventory.find(i=>i.item==='ironblade')!;
  const data=await page.evaluateHandle(()=>new DataTransfer());await page.locator(`[data-uid="${sword.uid}"]`).dispatchEvent('dragstart',{dataTransfer:data});const bag=await page.locator('#bag-grid').boundingBox();await page.locator('#bag-grid').dispatchEvent('drop',{dataTransfer:data,clientX:bag!.x+7*34+10,clientY:bag!.y+5*34+10});await page.waitForFunction(uid=>{const i=(window as any).eter.state.me.inventory.find((i:any)=>i.uid===uid);return i.x===7&&i.y===5;},sword.uid);
  await page.locator(`[data-uid="${sword.uid}"]`).dblclick();await page.waitForFunction(uid=>(window as any).eter.state.me.equipment.weapon.uid===uid,sword.uid);await page.keyboard.press('Escape');
  await move(page,0,10);await move(page,0,3);
  let state=await readState(page),monster=state.monsters.find(m=>m.def==='sproutling'&&m.hp>0)!;const first=monster.id;
  await page.keyboard.press('1');await clickWorld(page,monster.x,monster.z,0.95);await page.waitForFunction(id=>(window as any).eter.state.me.target===id,first);await page.waitForFunction(id=>(window as any).eter.state.monsters.find((m:any)=>m.id===id).hp<=0,first,{timeout:20000});
  state=await readState(page);expect(state.me.level).toBeGreaterThanOrEqual(2);expect(state.me.points).toBeGreaterThanOrEqual(5);expect(state.loot.some(l=>l.item==='eter')).toBeTruthy();expect(state.loot.some(l=>l.item==='ironblade')).toBeTruthy();
  await page.screenshot({path:'docs/evidence/greenfields-loot.png'});
  for(const item of ['eter','crowns','health','ironblade']){state=await readState(page);const loot=state.loot.find(l=>l.item===item)!;await page.locator('.world-label.loot').filter({hasText:item==='eter'?'Fragmento de Éter':item==='crowns'?'Crowns':item==='health'?'Poción de salud':'Espada de vigilia'}).first().click();await page.waitForFunction(id=>!(window as any).eter.state.loot.some((l:any)=>l.id===id),loot.id);}
  state=await readState(page);expect(state.me.eter).toBe(1);expect(state.me.crowns).toBeGreaterThan(23);expect(state.me.inventory.filter(i=>i.item==='ironblade')).toHaveLength(2);
  await page.keyboard.press('c');const oldStrength=state.me.stats.strength;await page.locator('[data-stat="strength"]').click();await page.waitForFunction(n=>(window as any).eter.state.me.stats.strength===n,oldStrength+1);await page.screenshot({path:'docs/evidence/character.png'});await page.keyboard.press('Escape');
  state=await readState(page);monster=state.monsters.find(m=>m.def==='sproutling'&&m.hp>0&&m.id!==first)!;const mpBefore=state.me.mana;await page.keyboard.press('2');await clickWorld(page,monster.x,monster.z,0.95,'right');await page.waitForFunction(id=>(window as any).eter.state.monsters.find((m:any)=>m.id===id).hp<=0,monster.id,{timeout:20000});expect((await readState(page)).me.mana).toBeLessThan(mpBefore);
  await page.keyboard.press('w');await page.waitForFunction(()=>(window as any).eter.state.me.mana>35);
  state=await readState(page);monster=state.monsters.find(m=>m.def==='sproutling'&&m.hp>0)!;await page.keyboard.press('3');await clickWorld(page,monster.x,monster.z,0.95);await page.waitForFunction(()=>(window as any).eter.state.events.some((e:any)=>e.type==='skill'&&e.skill==='sweep'),undefined,{timeout:20000});await page.keyboard.press('Escape');
  await page.waitForFunction(id=>(window as any).eter.state.monsters.find((m:any)=>m.id===id).hp>0,first,{timeout:15000});
  state=await readState(page);await move(page,0,2);await move(page,0,10);await move(page,0,17);
  await page.locator('.world-label.npc').filter({hasText:'Brom'}).click();await page.waitForFunction(()=>(window as any).eter.state.me.npc==='brom');const beforeRepair=await readState(page);expect(beforeRepair.me.equipment.weapon!.durability).toBeLessThan(80);await page.locator('#repair-button').click();await page.waitForFunction(()=>(window as any).eter.state.me.equipment.weapon.durability===80);await page.keyboard.press('Escape');
  await page.locator('[data-panel="account"]').click();const username=`vanguard_${Date.now().toString(36)}`;await page.locator('[name="username"]').fill(username);await page.locator('[name="password"]').fill('browser-test-password');await page.locator('[name="register"]').click();await expect(page.locator('#account-result')).toHaveText('Cuenta registrada.');
  const saved=(await readState(page)).me;await page.goto('about:blank');
  const context=await browser.newContext({baseURL:'http://127.0.0.1:3101',viewport:{width:1440,height:900}});const login=await context.request.post('/api/login',{data:{username,password:'browser-test-password'}});expect(login.ok()).toBeTruthy();const returned=await context.newPage();await ready(returned);const restored=(await readState(returned)).me;expect(restored.id).toBe(saved.id);expect(restored.eter).toBe(saved.eter);expect(restored.crowns).toBe(saved.crowns);expect(restored.stats).toEqual(saved.stats);expect(restored.inventory).toEqual(saved.inventory);expect(restored.equipment).toEqual(saved.equipment);expect(restored.level).toBe(saved.level);
  await returned.mouse.move(400,400);await returned.mouse.wheel(0,10000);await returned.waitForTimeout(300);expect(await returned.evaluate(()=>(window as any).eter.scene.view)).toBeLessThanOrEqual(25);await context.close();expect(errors).toEqual([]);
});

test('structured admin CRUD, nested editors, validation, shops, balance and click-to-place map',async({page,request})=>{
  test.setTimeout(240000);await authorize(request);await config(request);await ready(page);
  await page.locator('[data-panel="account"]').click();await page.locator('#admin-button').click();await expect(page.locator('.admin-login')).toBeVisible();await page.locator('.admin-login [name="token"]').fill(readFileSync(join(process.env.ETER_BROWSER_DATA!,'admin-token.txt'),'utf8').trim());await page.getByRole('button',{name:'Abrir editor'}).click();await expect(page.locator('[data-tab="NPCs"]')).toBeVisible();await page.locator('[data-tab="NPCs"]').click();
  await page.locator('#create-row').click();await page.locator('[data-field="npcs.2.id"]').fill('testnpc');await page.locator('[data-field="npcs.2.id"]').blur();await page.locator('[data-field="npcs.2.name"]').fill('Herrero de prueba');await page.locator('[data-field="npcs.2.name"]').blur();await page.locator('[data-field="npcs.2.x"]').fill('-3');await page.locator('[data-field="npcs.2.x"]').blur();await page.locator('[data-field="npcs.2.z"]').fill('23');await page.locator('[data-field="npcs.2.z"]').blur();
  await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toContainText('persistido');await page.locator('#duplicate-row').click();await expect(page.locator('[data-record]')).toHaveCount(4);page.once('dialog',d=>d.accept());await page.locator('#delete-row').click();await expect(page.locator('[data-record]')).toHaveCount(3);await page.locator('[data-field="npcs.2.enabled"]').uncheck();await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toContainText('persistido');
  await page.locator('[data-tab="Monsters"]').click();await page.locator('[data-field="monsters.0.hp"]').fill('-3');await page.locator('[data-field="monsters.0.hp"]').blur();await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toHaveClass(/error/);expect((await(await request.get('/api/admin/content')).json()).content.monsters[0].hp).toBe(68);await page.locator('[data-field="monsters.0.hp"]').fill('72');await page.locator('[data-field="monsters.0.hp"]').blur();await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toContainText('persistido');
  await page.locator('[data-tab="Spots"]').click();await page.locator('[data-field="spots.0.quantity"]').fill('6');await page.locator('[data-field="spots.0.quantity"]').blur();await page.locator('[data-field="spots.0.respawn"]').fill('8');await page.locator('[data-field="spots.0.respawn"]').blur();
  await page.locator('[data-tab="Drops"]').click();await page.locator('[data-field="dropTables.0.entries.0.chance"]').fill('0.8');await page.locator('[data-field="dropTables.0.entries.0.chance"]').blur();
  await page.locator('[data-tab="Items"]').click();await page.locator('[data-record="2"]').click();await page.locator('[data-field="items.2.buyPrice"]').fill('14');await page.locator('[data-field="items.2.buyPrice"]').blur();
  await page.locator('[data-tab="Shops"]').click();await page.locator('[data-shop="1"]').click();await page.locator('[data-field="npcs.1.shop.0.price"]').fill('14');await page.locator('[data-field="npcs.1.shop.0.price"]').blur();
  await page.locator('[data-tab="Classes"]').click();await page.locator('[data-field="classes.0.moveSpeed"]').fill('5.6');await page.locator('[data-field="classes.0.moveSpeed"]').blur();
  await page.locator('[data-tab="Balance"]').click();await page.locator('[data-field="balance.lootOwnership"]').fill('35');await page.locator('[data-field="balance.lootOwnership"]').blur();await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toContainText('persistido');
  const updated=(await(await request.get('/api/admin/content')).json()).content;expect(updated.spots[0].quantity).toBe(6);expect(updated.spots[0].respawn).toBe(8);expect(updated.dropTables[0].entries[0].chance).toBe(0.8);expect(updated.npcs[1].shop[0].price).toBe(14);expect(updated.classes[0].moveSpeed).toBe(5.6);expect(updated.balance.lootOwnership).toBe(35);
  await page.locator('[data-tab="Map"]').click();await page.locator('#map-target').selectOption('npcs.2');await page.locator('#admin-map').click({position:{x:100,y:340}});await page.locator('#admin-save').click();await expect(page.locator('#admin-status')).toContainText('persistido');const moved=(await(await request.get('/api/admin/content')).json()).content.npcs[2];expect(moved.x).not.toBe(-3);expect(moved.z).not.toBe(23);await page.screenshot({path:'docs/evidence/admin-map.png'});
  await page.locator('[data-tab="Players"]').click();await expect(page.locator('.player-table details').first()).toBeVisible();await page.locator('[data-tab="Raw Config"]').click();await page.locator('#raw-config').fill('{invalid');await page.locator('#raw-import').click();await expect(page.locator('#admin-status')).toHaveClass(/error/);
  await config(request);
});

test('HTTP admin validation and WebSocket reject unauthenticated, cross-origin and client-authority attempts',async({page,request})=>{
  expect((await request.get('/api/admin/content')).status()).toBe(401);await authorize(request);const current=await(await request.get('/api/admin/content')).json(),bad=structuredClone(current.content);bad.spots[0].monster='nonexistent';expect((await request.put('/api/admin/content',{data:{content:bad,revision:current.revision}})).status()).toBe(400);expect((await request.put('/api/admin/content',{data:{content:current.content,revision:-1}})).status()).toBe(409);
  const cross=await request.post('/api/admin/login',{headers:{Origin:'https://attacker.invalid'},data:{token:'invalid'}});expect(cross.status()).toBe(403);
  await page.goto('/api/session');const result=await page.evaluate(async()=>await new Promise<{before:any;after:any}>(resolve=>{const ws=new WebSocket(`ws://${location.host}/world`);let first:any,count=0;ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.type!=='state')return;if(!first){first=d.me;for(const intent of [{type:'money',crowns:100000},{type:'move',x:0,z:10,hp:99999},{type:'equip',uid:'forged'},{type:'buy',npc:'lyra',item:'eter',price:-1}])ws.send(JSON.stringify(intent));}else if(++count>3){ws.close();resolve({before:first,after:d.me});}};}));expect(result.after.crowns).toBe(result.before.crowns);expect(result.after.eter).toBe(0);expect(result.after.inventory).toEqual(result.before.inventory);expect(result.after.x).toBe(result.before.x);expect(result.after.z).toBe(result.before.z);
});
