import type { Content } from '../shared/content';
import { validateContent } from '../shared/content';
import defaults from '../content/default.json';
import { esc } from './icons';
const tabs=['Overview','NPCs','Monsters','Spots','Drops','Items','Shops','Classes','Balance','Map','Players','Raw Config'];
const collections:Record<string,keyof Content>={NPCs:'npcs',Monsters:'monsters',Spots:'spots',Drops:'dropTables',Items:'items',Classes:'classes'};
const names:Record<string,string>={id:'ID interno',name:'Nombre',style:'Modelo / estilo',x:'Posición X',z:'Posición Z',facing:'Orientación (radianes)',role:'Rol',dialogue:'Diálogo',interaction:'Interacción',enabled:'Habilitado',shop:'Inventario de tienda',services:'Servicios',item:'Objeto',price:'Precio (Crowns)',order:'Orden',category:'Categoría',hp:'Vida',damage:'Daño',defense:'Defensa',xp:'Experiencia',moveSpeed:'Velocidad (u/s)',attackSpeed:'Intervalo de ataque (s)',attackRange:'Alcance',aggroRadius:'Radio de agresión',leash:'Distancia de retorno',behavior:'Comportamiento',dropTable:'Tabla de drops',map:'Mapa',monster:'Criatura',radius:'Radio',quantity:'Cantidad',respawn:'Respawn (s)',entries:'Entradas',chance:'Probabilidad (0–1)',min:'Cantidad mínima',max:'Cantidad máxima',monsters:'Restricción de criaturas',type:'Tipo',model:'Modelo de objeto',icon:'Icono',width:'Ancho en celdas',height:'Alto en celdas',requirements:'Requisitos',durability:'Durabilidad',classAffinity:'Afinidad de clase',buyPrice:'Precio de compra',sellPrice:'Precio de venta',droppable:'Puede caer',tradeable:'Transferible en el futuro',properties:'Propiedades extensibles',startingStats:'Atributos iniciales',startingHP:'Vida inicial',startingMana:'Maná inicial',startingWeapon:'Arma inicial',scaling:'Escala por atributo',strength:'Fuerza',agility:'Agilidad',vitality:'Vitalidad',energy:'Energía',mana:'Maná',xpBase:'Base de XP',xpExponent:'Exponente de XP',pointsPerLevel:'Puntos por nivel',maxLevel:'Nivel máximo (hasta 500)',crownsMultiplier:'Multiplicador de Crowns',eterChance:'Probabilidad base de Éter',lootOwnership:'Reserva del botín (s)',lootLifetime:'Duración del botín (s)',movementMultiplier:'Multiplicador de movimiento',death:'Reglas de muerte',xpLoss:'Pérdida de XP (0–1)',crownsLoss:'Pérdida de Crowns (0–1)',respawnSeconds:'Regreso a ciudad (s)',daylight:'Luz ambiental',spawn:'Spawn',safeZone:'Límites de zona segura',bounds:'Límites del mapa',camera:'Cámara',landmarks:'Landmarks',offsetX:'Offset X',offsetZ:'Offset Z',viewSize:'Zoom inicial',minView:'Zoom mínimo',maxView:'Zoom máximo'};
export class Admin {
  el:HTMLElement;draft:Content|null=null;revision=0;tab='Overview';index=0;dirty=false;mapTarget='spawn';mapCanvas:HTMLCanvasElement|null=null;
  constructor(readonly parent:HTMLElement){this.el=document.createElement('div');this.el.id='admin-overlay';this.el.hidden=true;parent.append(this.el);}
  async open(){this.el.hidden=false;try{await this.load();}catch{this.login();}}
  async api(path:string,method='GET',body?:unknown){const r=await fetch(`/api/admin/${path}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const json=await r.json();if(!r.ok)throw new Error(json.error);return json;}
  login(){this.el.innerHTML=`<div class="admin-login"><button class="admin-close">×</button><span class="admin-kicker">ÉTER / CONTENT STUDIO</span><h2>Acceso administrativo</h2><p>Ingresa la clave del servidor, ubicada en <code>.data/admin-token.txt</code>.</p><form><label>Clave<input name="token" type="password" autocomplete="off" required></label><button type="submit">Abrir editor</button></form><p class="admin-error" role="status"></p></div>`;this.el.querySelector<HTMLButtonElement>('.admin-close')!.onclick=()=>this.el.hidden=true;this.el.querySelector<HTMLFormElement>('form')!.onsubmit=async e=>{e.preventDefault();try{await this.api('login','POST',{token:new FormData(e.target as HTMLFormElement).get('token')});await this.load();}catch(err){this.el.querySelector('.admin-error')!.textContent=(err as Error).message;}};}
  async load(){const data=await this.api('content');this.draft=structuredClone(data.content);this.revision=data.revision;this.dirty=false;this.render();}
  read(path:string):any{return path.split('.').reduce((v,key)=>v?.[key],this.draft as any);}
  write(path:string,value:unknown){const keys=path.split('.'),last=keys.pop()!,parent=this.read(keys.join('.'));parent[last]=value;this.dirty=true;this.status('Cambios sin aplicar. El servidor validará toda la configuración.');}
  status(message:string,error=false){const el=this.el.querySelector<HTMLElement>('#admin-status');if(el){el.textContent=message;el.classList.toggle('error',error);}}
  choices(path:string):string[]|null{
    const key=path.split('.').at(-1)!,c=this.draft!;
    if(key==='monster')return c.monsters.map(m=>m.id);
    if(key==='item'||key==='startingWeapon')return c.items.filter(i=>key!=='startingWeapon'||i.type==='weapon').map(i=>i.id);
    if(key==='dropTable')return c.dropTables.map(t=>t.id);
    if(key==='map')return[c.world.id];
    if(key==='behavior')return['passive','aggressive'];
    if(key==='interaction')return['shop','repair','storage','teleporter','trainer','reset','custom'];
    if(key==='type'&&path.startsWith('items'))return['currency','resource','consumable','weapon','chest','boots','helmet','pants','gloves','offhand','wings','necklace','ring1','ring2'];
    if(key==='style')return path.startsWith('npcs')?['blacksmith','merchant']:path.startsWith('monsters')?['sproutling','forestwolf']:['crystal','forge','market','house','wall'];
    return null;
  }
  fields(value:any,path:string):string{
    if(Array.isArray(value)){
      const key=path.split('.').at(-1)!;
      if(['monsters','classAffinity','services'].includes(key)){const options=key==='monsters'?this.draft!.monsters.map(m=>m.id):key==='classAffinity'?this.draft!.classes.map(c=>c.id):['repair'];return`<fieldset><legend>${esc(names[key]??key)}</legend><div class="admin-checks">${options.map(option=>`<label><input type="checkbox" data-list="${esc(path)}" value="${esc(option)}" ${value.includes(option)?'checked':''}>${esc(option)}</label>`).join('')}</div></fieldset>`;}
      return`<fieldset class="admin-array"><legend>${esc(names[key]??key)}</legend>${value.map((row,i)=>`<div class="admin-array-row"><div class="row-number">${i+1}<button type="button" data-remove="${esc(path)}" data-index="${i}" title="Quitar fila">×</button></div>${this.fields(row,`${path}.${i}`)}</div>`).join('')}<button type="button" data-add="${esc(path)}">+ Añadir ${esc(names[key]??key)}</button></fieldset>`;
    }
    if(value!==null&&typeof value==='object'){
      const key=path.split('.').at(-1)??'',isRoot=!path||/^\w+\.\d+$/.test(path),fields=Object.entries(value).map(([k,v])=>this.fields(v,path?`${path}.${k}`:k)).join('');
      return isRoot?fields:`<fieldset><legend>${esc(names[key]??key)}</legend><div class="admin-fields">${fields}</div>${key==='properties'||key==='requirements'?`<div class="property-add"><input placeholder="Nombre de propiedad" data-property-name="${esc(path)}"><input type="number" value="0" data-property-value="${esc(path)}"><button type="button" data-property-add="${esc(path)}">Añadir propiedad</button></div>`:''}</fieldset>`;
    }
    const key=path.split('.').at(-1)!,options=this.choices(path),label=names[key]??key;
    if(typeof value==='boolean')return`<label class="admin-boolean"><input type="checkbox" data-field="${esc(path)}" data-kind="boolean" ${value?'checked':''}>${esc(label)}</label>`;
    if(options)return`<label>${esc(label)}<select data-field="${esc(path)}" data-kind="string">${options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
    if(key==='dialogue')return`<label class="wide">${esc(label)}<textarea data-field="${esc(path)}" data-kind="string" rows="3">${esc(value)}</textarea></label>`;
    return`<label>${esc(label)}<input data-field="${esc(path)}" data-kind="${typeof value}" type="${typeof value==='number'?'number':'text'}" ${typeof value==='number'?'step="any"':''} value="${esc(value)}"></label>`;
  }
  rows():any[]{const key=collections[this.tab];return key?(this.draft as any)[key]:[];}
  render(){if(!this.draft)return;const c=this.draft;
    this.el.innerHTML=`<div class="admin-shell"><header class="admin-header"><div><span class="admin-kicker">ÉTER / CONTENT STUDIO</span><h2>Goal 0 · editor del mundo</h2></div><div class="admin-actions"><button id="admin-reload">Recargar</button><button id="admin-export">Exportar</button><button id="admin-save" class="primary">Validar y aplicar</button><button class="admin-close" aria-label="Cerrar editor">×</button></div></header><div class="admin-layout"><nav>${tabs.map(t=>`<button data-tab="${t}" class="${t===this.tab?'active':''}">${t}</button>`).join('')}</nav><main id="admin-main"></main></div><footer id="admin-status" role="status">${this.dirty?'Cambios sin aplicar':'Configuración del servidor · revisión '+this.revision}</footer></div>`;
    this.el.querySelector<HTMLButtonElement>('.admin-close')!.onclick=()=>this.el.hidden=true;
    this.el.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab!;this.index=0;this.render();});
    this.el.querySelector<HTMLButtonElement>('#admin-reload')!.onclick=async()=>{if(this.dirty&&!confirm('¿Descartar cambios sin aplicar y recargar el servidor?'))return;try{await this.load();}catch(e){this.status((e as Error).message,true);}};
    this.el.querySelector<HTMLButtonElement>('#admin-export')!.onclick=()=>{const link=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(c,null,2)],{type:'application/json'}));link.href=url;link.download='eter-content.json';link.click();URL.revokeObjectURL(url);};
    this.el.querySelector<HTMLButtonElement>('#admin-save')!.onclick=()=>this.save();
    const main=this.el.querySelector<HTMLElement>('#admin-main')!;
    if(collections[this.tab]){
      const rows=this.rows();this.index=Math.min(this.index,Math.max(0,rows.length-1));const row=rows[this.index];
      main.innerHTML=`<div class="admin-section-heading"><h3>${this.tab}</h3><div><button id="create-row">+ Crear</button><button id="duplicate-row" ${!row?'disabled':''}>Duplicar</button><button id="delete-row" ${!row?'disabled':''}>Eliminar</button></div></div><div class="admin-records">${rows.map((r,i)=>`<button data-record="${i}" class="${i===this.index?'active':''}"><b>${esc(r.name)}</b><small>${esc(r.id)} ${r.enabled===false?'· deshabilitado':''}</small></button>`).join('')}</div><div class="admin-fields">${row?this.fields(row,`${collections[this.tab]}.${this.index}`):'<p>No hay registros. Crea uno.</p>'}</div>`;
      main.querySelectorAll<HTMLButtonElement>('[data-record]').forEach(b=>b.onclick=()=>{this.index=Number(b.dataset.record);this.render();});
      main.querySelector<HTMLButtonElement>('#create-row')!.onclick=()=>this.create(false);
      main.querySelector<HTMLButtonElement>('#duplicate-row')!.onclick=()=>this.create(true);
      main.querySelector<HTMLButtonElement>('#delete-row')!.onclick=()=>{if(!confirm(`¿Eliminar ${row.name}? Las referencias deben corregirse antes de aplicar.`))return;rows.splice(this.index,1);this.dirty=true;this.render();};
    }else if(this.tab==='Overview'){
      main.innerHTML=`<h3>Una ciudad. Un camino. Un mundo por sentir.</h3><p class="admin-intro">Autoridad de servidor a 30 Hz. Los cambios se guardan en SQLite y llegan a los clientes conectados. Aplicar contenido reinicia los spots y retira el botín de la sesión.</p><div class="overview-cards">${[['NPCs',c.npcs.length],['Monsters',c.monsters.length],['Spots',c.spots.length],['Items',c.items.length],['Drops',c.dropTables.length],['Classes',c.classes.length]].map(([key,count])=>`<button data-overview-tab="${key}"><strong>${count}</strong><span>${key}</span></button>`).join('')}</div><h4>Flujo de edición</h4><ol><li>Selecciona una sección y modifica sus campos.</li><li>Usa Map para mover spawn, NPCs, spots o landmarks.</li><li>Valida y aplica. Ningún cambio inválido modifica el mundo.</li></ol><p>Storage, teleporter, trainer, reset y custom son tipos reservados. Goal 0 solo ejecuta tiendas y reparación.</p><p class="admin-intro">Este editor es una herramienta administrativa del prototipo, no parte del HUD del jugador.</p>`;
      main.querySelectorAll<HTMLButtonElement>('[data-overview-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.overviewTab!;this.index=0;this.render();});
    }else if(this.tab==='Balance'){main.innerHTML=`<h3>Balance</h3><p>XP(n) = base × nivel ^ exponente. Intervalos de ataque en segundos.</p><div class="admin-fields">${this.fields(c.balance,'balance')}${this.fields(c.skills,'skills')}</div>`;}
    else if(this.tab==='Shops'){const npc=c.npcs[this.index];main.innerHTML=`<h3>Shops</h3><div class="admin-records">${c.npcs.map((n,i)=>`<button data-shop="${i}" class="${i===this.index?'active':''}">${esc(n.name)}</button>`).join('')}</div>${npc?`<h4>${esc(npc.name)} · ${esc(npc.interaction)}</h4>${this.fields(npc.shop,`npcs.${this.index}.shop`)}${this.fields(npc.services,`npcs.${this.index}.services`)}`:'Crea un NPC en NPCs.'}`;main.querySelectorAll<HTMLButtonElement>('[data-shop]').forEach(b=>b.onclick=()=>{this.index=Number(b.dataset.shop);this.render();});}
    else if(this.tab==='Map'){this.renderMap(main);}
    else if(this.tab==='Players'){main.innerHTML='<h3>Players</h3><p>Cargando personajes persistidos…</p>';this.api('players').then(rows=>{if(this.tab!=='Players')return;main.innerHTML=`<h3>Players</h3><p>Inspección de cuentas y personajes. No se implementa edición de jugadores en Goal 0.</p><div class="player-table">${rows.map((r:any)=>`<details><summary>${esc(r.name)} · ${r.online?'conectado':'desconectado'} · nivel ${r.character?.level??1}</summary><dl><dt>Cuenta</dt><dd>${esc(r.id)}</dd><dt>Registrada</dt><dd>${r.registered?'Sí':'Invitado'}</dd><dt>XP / puntos</dt><dd>${r.character?.xp??0} / ${r.character?.points??0}</dd><dt>Crowns / Éter</dt><dd>${r.character?.crowns??100} / ${r.character?.eter??0}</dd><dt>Posición</dt><dd>${r.character?.x?.toFixed(1)??0}, ${r.character?.z?.toFixed(1)??0}</dd><dt>Inventario</dt><dd>${esc(r.character?.inventory.map((i:any)=>i.item).join(', ')??'Sin datos guardados')}</dd><dt>Equipo</dt><dd>${esc(Object.entries(r.character?.equipment??{}).map(([slot,i]:any)=>slot+': '+i.item).join(', '))}</dd><dt>Atributos</dt><dd>${esc(Object.entries(r.character?.stats??{}).map(([key,value])=>key+': '+value).join(', '))}</dd></dl></details>`).join('')}</div>`;}).catch(e=>this.status(e.message,true));}
    else if(this.tab==='Raw Config'){main.innerHTML=`<h3>Raw Config · avanzado</h3><p>La edición estructurada está en las otras secciones. Importar pasa por el mismo validador.</p><textarea id="raw-config" spellcheck="false">${esc(JSON.stringify(c,null,2))}</textarea><button id="raw-import">Cargar JSON al borrador</button>`;main.querySelector<HTMLButtonElement>('#raw-import')!.onclick=()=>{try{this.draft=validateContent(JSON.parse(main.querySelector<HTMLTextAreaElement>('#raw-config')!.value));this.dirty=true;this.status('JSON válido cargado al borrador. Aplica para guardar.');}catch(e){this.status((e as Error).message,true);}};}
    this.bindFields();
  }
  bindFields(){
    this.el.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(input=>input.onchange=()=>{let value:unknown=input.value;if(input.dataset.kind==='number')value=Number(input.value);if(input.dataset.kind==='boolean')value=(input as HTMLInputElement).checked;this.write(input.dataset.field!,value);if(this.tab==='Map')this.drawMap();});
    this.el.querySelectorAll<HTMLInputElement>('[data-list]').forEach(input=>input.onchange=()=>{const path=input.dataset.list!,values=this.read(path) as string[];this.write(path,input.checked?[...new Set([...values,input.value])]:values.filter(v=>v!==input.value));});
    this.el.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>{this.read(b.dataset.remove!).splice(Number(b.dataset.index),1);this.dirty=true;this.render();});
    this.el.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.onclick=()=>{const path=b.dataset.add!,key=path.split('.').at(-1)!;let row:any;
      if(key==='shop')row={item:this.draft!.items.find(i=>i.type==='consumable')?.id??this.draft!.items[0].id,price:10,order:this.read(path).length,category:'General'};
      else if(key==='entries')row={item:'crowns',chance:0.1,min:1,max:1,monsters:[],enabled:true};
      else if(key==='landmarks')row={...structuredClone(defaults.world.landmarks[0]),id:`landmark${Date.now().toString(36)}`,name:'Nuevo landmark',x:10,z:0};
      else if(key==='skills'){this.status('Goal 0 requiere exactamente tres acciones de combate.',true);return;}
      else{this.status('Tipo de colección no editable aquí.',true);return;}
      this.read(path).push(row);this.dirty=true;this.render();});
    this.el.querySelectorAll<HTMLButtonElement>('[data-property-add]').forEach(b=>b.onclick=()=>{const path=b.dataset.propertyAdd!,name=(this.el.querySelector(`[data-property-name="${path}"]`) as HTMLInputElement).value.trim(),value=Number((this.el.querySelector(`[data-property-value="${path}"]`) as HTMLInputElement).value);if(!/^[a-zA-Z][a-zA-Z0-9_]{0,39}$/.test(name)||['__proto__','constructor','prototype'].includes(name)){this.status('Nombre de propiedad inválido',true);return;}this.read(path)[name]=value;this.dirty=true;this.render();});
  }
  create(duplicate:boolean){const rows=this.rows(),key=collections[this.tab],row=structuredClone(duplicate?rows[this.index]:(defaults as any)[key][0]);row.id=`${String(row.id).slice(0,20)}_${Date.now().toString(36)}`;row.name=duplicate?`${row.name} copia`:`Nuevo ${this.tab}`;if(this.tab==='Classes')row.enabled=false;rows.push(row);this.index=rows.length-1;this.dirty=true;this.render();}
  async save(){try{if(this.tab==='Raw Config'&&this.el.querySelector('#raw-config'))this.draft=validateContent(JSON.parse((this.el.querySelector('#raw-config') as HTMLTextAreaElement).value));const content=validateContent(this.draft);const result=await this.api('content','PUT',{content,revision:this.revision});this.revision=result.revision;this.dirty=false;this.status(`Contenido aplicado y persistido · revisión ${this.revision}`);}catch(e){this.status((e as Error).message,true);}}
  renderMap(main:HTMLElement){const c=this.draft!;main.innerHTML=`<h3>Map · coordenadas del mundo</h3><p>Elige una entidad y haz clic en el mapa para moverla. Las posiciones se aplican después de validar.</p><div class="map-editor"><div><select id="map-target"><option value="spawn">Spawn</option>${c.npcs.map((n,i)=>`<option value="npcs.${i}">NPC · ${esc(n.name)}</option>`).join('')}${c.spots.map((s,i)=>`<option value="spots.${i}">Spot · ${esc(s.name)}</option>`).join('')}${c.world.landmarks.map((l,i)=>`<option value="world.landmarks.${i}">Landmark · ${esc(l.name)}</option>`).join('')}</select><canvas id="admin-map" width="420" height="460"></canvas></div><div class="admin-fields">${this.fields(c.world.spawn,'world.spawn')}${this.fields(c.world.safeZone,'world.safeZone')}${this.fields(c.world.bounds,'world.bounds')}${this.fields(c.world.camera,'world.camera')}</div></div>${this.fields(c.world.landmarks,'world.landmarks')}`;
    this.mapCanvas=main.querySelector('#admin-map')!;const select=main.querySelector<HTMLSelectElement>('#map-target')!;select.value=this.mapTarget;if(!select.value){this.mapTarget='spawn';select.value='spawn';}select.onchange=()=>{this.mapTarget=select.value;this.drawMap();};
    this.mapCanvas.onclick=e=>{const rect=this.mapCanvas!.getBoundingClientRect(),b=c.world.bounds,path=this.mapTarget==='spawn'?'world.spawn':this.mapTarget;const point={x:Math.round((b.minX+(e.clientX-rect.left)/rect.width*(b.maxX-b.minX))*10)/10,z:Math.round((b.minZ+(e.clientY-rect.top)/rect.height*(b.maxZ-b.minZ))*10)/10};this.write(`${path}.x`,point.x);this.write(`${path}.z`,point.z);this.render();};this.drawMap();
  }
  drawMap(){const canvas=this.mapCanvas,c=this.draft;if(!canvas||!c)return;const ctx=canvas.getContext('2d')!,w=canvas.width,h=canvas.height,b=c.world.bounds,px=(x:number)=>(x-b.minX)/(b.maxX-b.minX)*w,pz=(z:number)=>(z-b.minZ)/(b.maxZ-b.minZ)*h;ctx.fillStyle='#23352e';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#3c5045';ctx.lineWidth=1;
    for(let x=b.minX;x<b.maxX;x+=2){ctx.beginPath();ctx.moveTo(px(x),0);ctx.lineTo(px(x),h);ctx.stroke();}for(let z=b.minZ;z<b.maxZ;z+=2){ctx.beginPath();ctx.moveTo(0,pz(z));ctx.lineTo(w,pz(z));ctx.stroke();}
    const s=c.world.safeZone;ctx.fillStyle='#796e4644';ctx.fillRect(px(s.minX),pz(s.minZ),px(s.maxX)-px(s.minX),pz(s.maxZ)-pz(s.minZ));ctx.font='11px sans-serif';
    for(const l of c.world.landmarks){ctx.fillStyle='#a49c7b';ctx.fillRect(px(l.x-l.width/2),pz(l.z-l.depth/2),l.width/(b.maxX-b.minX)*w,l.depth/(b.maxZ-b.minZ)*h);ctx.fillStyle='#fff0c0';ctx.fillText(l.name,px(l.x)-20,pz(l.z)-6);}
    for(const spot of c.spots){ctx.strokeStyle=spot.enabled?'#d59a73':'#727e72';ctx.beginPath();ctx.ellipse(px(spot.x),pz(spot.z),spot.radius/(b.maxX-b.minX)*w,spot.radius/(b.maxZ-b.minZ)*h,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#eac9a3';ctx.fillText(spot.name,px(spot.x)-25,pz(spot.z));}
    for(const npc of c.npcs){ctx.fillStyle=npc.enabled?'#e6ce80':'#747c74';ctx.fillRect(px(npc.x)-4,pz(npc.z)-4,8,8);ctx.fillText(npc.name,px(npc.x)+6,pz(npc.z));}
    ctx.fillStyle='#80e5cd';ctx.beginPath();ctx.arc(px(c.world.spawn.x),pz(c.world.spawn.z),5,0,Math.PI*2);ctx.fill();ctx.fillText('Spawn',px(c.world.spawn.x)+7,pz(c.world.spawn.z));
    const selected=this.read(this.mapTarget==='spawn'?'world.spawn':this.mapTarget);if(selected){ctx.strokeStyle='#fff7d0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px(selected.x),pz(selected.z),9,0,Math.PI*2);ctx.stroke();}
  }
}
