import type { Content, Stats } from '../shared/content';
import type { Action, PlayerState, Snapshot } from '../shared/protocol';
import type { GameScene } from './scene';
import { esc, icon } from './icons';
export class GameUI {
  panel:string|null=null;content:Content;state:Snapshot|null=null;bagHash='';npcHash='';lastEvents=new Set<number>();
  chosenSkill='strike';skillAt=0;
  hud:HTMLElement;panelEl:HTMLElement;shopEl:HTMLElement;logEl:HTMLElement;map:HTMLCanvasElement;adminOpen:()=>void=()=>{};
  constructor(readonly root:HTMLElement,content:Content,readonly send:(a:Action)=>void){this.content=content;
    root.innerHTML=`<canvas id="world-canvas" aria-label="Mundo de Éter. Clic para caminar o atacar."></canvas><div id="world-labels"></div>
      <div class="vignette"></div><div id="zone"><span class="zone-emblem">◇</span><div><h1>AURELIA</h1><p id="zone-status">Refugio seguro</p></div></div>
      <aside id="minimap-frame"><div class="map-heading"><span>GREENFIELDS</span><span>N ↑</span></div><canvas id="minimap" width="160" height="150" aria-label="Minimapa de Aurelia y Greenfields"></canvas><div id="coords"></div></aside>
      <div id="target-info" hidden></div><div id="connection">Conectando con Aurelia…</div><div id="notice" role="status"></div>
      <div id="game-log" aria-live="polite"><p>Éter · prototipo Goal 0</p><p>Sal de Aurelia por la puerta sur.</p></div>
      <section id="game-panel" class="game-panel" hidden></section><section id="shop-panel" class="game-panel" hidden></section>
      <footer id="hud"><div class="hud-inner"><div class="identity"><b>VANGUARD</b><span id="level">Nivel 1</span><div id="balances"></div></div>
      <div class="vitals"><div class="vital health"><span>VIDA</span><b id="hp-text"></b><i id="hp-fill"></i></div><div class="vital mana"><span>MANÁ</span><b id="mp-text"></b><i id="mp-fill"></i></div></div>
      <div class="skills">${content.skills.map((s,i)=>`<button class="slot skill" data-skill="${esc(s.id)}" title="${esc(s.name)} · ${s.mana} maná"><kbd>${i+1}</kbd>${icon(['sword','cleave','sweep'][i])}<span>${esc(s.name)}</span></button>`).join('')}</div>
      <div class="potions"><button class="slot small" data-use="health" title="Poción de salud [Q]"><kbd>Q</kbd>${icon('health')}<b id="hp-count">0</b></button><button class="slot small" data-use="mana" title="Poción de maná [W]"><kbd>W</kbd>${icon('mana')}<b id="mp-count">0</b></button></div>
      <nav><button data-panel="inventory" title="Inventario [I]">${icon('bag')}<kbd>I</kbd></button><button data-panel="character" title="Personaje [C]">${icon('character')}<kbd>C</kbd></button><button data-panel="map" title="Mapa [M]">${icon('map')}<kbd>M</kbd></button><button data-panel="help" title="Controles [H]">?<kbd>H</kbd></button><button data-panel="account" title="Cuenta">⚙</button></nav></div>
      <div class="exp-track"><i id="xp-fill"></i><span id="xp-text"></span></div></footer><div id="performance" hidden></div>`;
    this.hud=root.querySelector('#hud')!;this.panelEl=root.querySelector('#game-panel')!;this.shopEl=root.querySelector('#shop-panel')!;this.logEl=root.querySelector('#game-log')!;this.map=root.querySelector('#minimap')!;
    this.chosenSkill=content.skills[0].id;
    root.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>b.onclick=()=>this.chooseSkill(b.dataset.skill!));
    root.querySelectorAll<HTMLButtonElement>('[data-use]').forEach(b=>b.onclick=()=>this.send({type:'use',item:b.dataset.use!}));
    root.querySelectorAll<HTMLButtonElement>('[data-panel]').forEach(b=>b.onclick=()=>this.toggle(b.dataset.panel!));
    window.addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('input,textarea,select')||document.querySelector('#admin-overlay:not([hidden])'))return;const k=e.key.toLowerCase();if(k==='i')this.toggle('inventory');else if(k==='c')this.toggle('character');else if(k==='m')this.toggle('map');else if(k==='h'||k==='f1'){e.preventDefault();this.toggle('help');}else if(k==='q')this.send({type:'use',item:'health'});else if(k==='w')this.send({type:'use',item:'mana'});else if(['1','2','3'].includes(k))this.chooseSkill(this.content.skills[Number(k)-1].id);else if(k===' '){e.preventDefault();const me=this.state?.me;if(!me)return;const nearest=this.state!.loot.filter(l=>l.owner===me.id||this.state!.time>=l.publicAt).sort((a,b)=>Math.hypot(a.x-me.x,a.z-me.z)-Math.hypot(b.x-me.x,b.z-me.z))[0];if(nearest)this.send({type:'pickup',id:nearest.id});}else if(k==='escape'){this.panel=null;this.panelEl.hidden=true;this.shopEl.hidden=true;this.send({type:'stop'});}else if(k==='f3'){e.preventDefault();const el=root.querySelector<HTMLElement>('#performance')!;el.hidden=!el.hidden;}});
  }
  chooseSkill(id:string){this.chosenSkill=id;this.skillAt=performance.now();this.send({type:'skill',id});}
  notify(text:string){const el=this.root.querySelector<HTMLElement>('#notice')!;el.textContent=text;el.classList.add('show');clearTimeout(this.noticeTimer);this.noticeTimer=window.setTimeout(()=>el.classList.remove('show'),2600);}
  noticeTimer=0;
  log(text:string){const p=document.createElement('p');p.textContent=text;this.logEl.append(p);while(this.logEl.children.length>6)this.logEl.firstElementChild?.remove();}
  toggle(panel:string){this.panel=this.panel===panel?null:panel;this.bagHash='';this.renderPanel();}
  setContent(content:Content){this.content=content;this.bagHash='';this.npcHash='';this.renderPanel();}
  update(s:Snapshot){this.state=s;const p=s.me;
    if(performance.now()-this.skillAt>150)this.chosenSkill=p.skill;
    this.root.querySelector('#level')!.textContent=`Nivel ${p.level}`;
    this.root.querySelector('#balances')!.innerHTML=`<span class="crowns">${icon('coins')} ${Math.floor(p.crowns)}</span><span class="eter">${icon('crystal')} ${p.eter}</span>`;
    this.root.querySelector('#hp-text')!.textContent=`${Math.ceil(p.hp)} / ${p.derived.maxHP}`;this.root.querySelector<HTMLElement>('#hp-fill')!.style.width=`${p.hp/p.derived.maxHP*100}%`;
    this.root.querySelector('#mp-text')!.textContent=`${Math.floor(p.mana)} / ${p.derived.maxMana}`;this.root.querySelector<HTMLElement>('#mp-fill')!.style.width=`${p.mana/p.derived.maxMana*100}%`;
    const needed=Math.round(this.content.balance.xpBase*Math.pow(p.level,this.content.balance.xpExponent));const max=p.level>=this.content.balance.maxLevel;
    this.root.querySelector<HTMLElement>('#xp-fill')!.style.width=`${max?100:p.xp/needed*100}%`;this.root.querySelector('#xp-text')!.textContent=max?'Nivel máximo del prototipo':`EXP ${p.xp} / ${needed}`;
    for(const kind of ['hp','mp'])this.root.querySelector(`#${kind}-count`)!.textContent=String(p.inventory.filter(i=>i.item===(kind==='hp'?'health':'mana')).length);
    this.root.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>b.classList.toggle('selected',b.dataset.skill===p.skill));
    const safe=p.x>=this.content.world.safeZone.minX&&p.x<=this.content.world.safeZone.maxX&&p.z>=this.content.world.safeZone.minZ&&p.z<=this.content.world.safeZone.maxZ;
    this.root.querySelector('#zone h1')!.textContent=safe?'AURELIA':'GREENFIELDS';this.root.querySelector('#zone-status')!.textContent=safe?'Refugio seguro':p.z>-10?'Claro del brote · Nv. 1':'Linde de los lobos · Nv. 3';
    this.root.querySelector('#coords')!.textContent=`${p.x.toFixed(0)}, ${p.z.toFixed(0)} · ${safe?'ZONA SEGURA':'CAMPO'}`;
    const target=s.monsters.find(m=>m.id===p.target&&m.hp>0),targetEl=this.root.querySelector<HTMLElement>('#target-info')!;targetEl.hidden=!target;
    if(target){const def=this.content.monsters.find(m=>m.id===target.def)!;targetEl.innerHTML=`<b>${esc(def.name)}</b><small>Nivel ${def.level}</small><div><i style="width:${target.hp/target.maxHP*100}%"></i></div><span>${Math.ceil(target.hp)} / ${target.maxHP}</span>`;}
    for(const e of s.events){if(this.lastEvents.has(e.id))continue;this.lastEvents.add(e.id);if(['message','loot','level'].includes(e.type)){this.log(e.text??'');if(e.type!=='loot')this.notify(e.text??'');}}
    if(this.lastEvents.size>500)this.lastEvents=new Set([...this.lastEvents].slice(-200));
    const hash=JSON.stringify([p.inventory,p.equipment,p.stats,p.points,p.level]);if(hash!==this.bagHash){this.bagHash=hash;this.renderPanel();}
    this.renderShop(p);this.drawMap(this.map);
    if(p.hp<=0)this.notify(`Has caído · regreso en ${Math.max(0,Math.ceil(p.deadUntil-s.time))} s`);
  }
  header(title:string){return`<header><h2>${title}</h2><button class="close" aria-label="Cerrar">×</button></header>`;}
  renderPanel(){const el=this.panelEl,p=this.state?.me;el.hidden=!this.panel;if(!this.panel)return;let html=this.header(({inventory:'Inventario',character:'Vanguard',map:'Aurelia & Greenfields',help:'Guía del caminante',account:'Cuenta y ajustes'} as Record<string,string>)[this.panel]??'Éter');
    if(this.panel==='inventory'&&p){html+=`<div class="equipment">${(['weapon','chest','boots'] as const).map(slot=>{const item=p.equipment[slot],def=this.content.items.find(d=>d.id===item?.item);return`<button class="equip-slot" data-unequip="${slot}" title="${def?esc(def.name)+' · '+Math.floor(item!.durability)+' durabilidad · doble clic para quitar':'Sin equipo'}">${def?icon(def.icon):'◇'}<span>${{weapon:'Arma',chest:'Coraza',boots:'Botas'}[slot]}</span></button>`;}).join('')}</div><p class="hint">Arrastra para ordenar · doble clic para equipar o usar</p><div id="bag-grid">${p.inventory.map(i=>{const def=this.content.items.find(d=>d.id===i.item)!;return`<button class="bag-item ${def.type}" draggable="true" data-uid="${i.uid}" style="left:${i.x*34}px;top:${i.y*34}px;width:${def.width*34-2}px;height:${def.height*34-2}px" title="${esc(def.name)}${def.damage?' · Daño +'+def.damage:''}${def.defense?' · Defensa +'+def.defense:''}${def.durability?' · Durabilidad '+Math.floor(i.durability)+'/'+def.durability:''}${Object.keys(def.requirements).length?' · Requiere '+Object.entries(def.requirements).map(([k,v])=>k+' '+v).join(', '):''}">${icon(def.icon)}</button>`;}).join('')}</div><div class="bag-footer"><span>${icon('coins')} ${Math.floor(p.crowns)} Crowns</span><span>${icon('crystal')} ${p.eter} Éter</span></div>`;}
    else if(this.panel==='character'&&p){html+=`<div class="character-title"><span>VANGUARD</span><b>Nivel ${p.level}</b></div><p class="points">Puntos disponibles <strong>${p.points}</strong></p><div class="stat-list">${(['strength','agility','vitality','energy'] as const).map(stat=>`<div><span>${{strength:'Fuerza',agility:'Agilidad',vitality:'Vitalidad',energy:'Energía'}[stat]}</span><b>${p.stats[stat]}</b><button data-stat="${stat}" ${p.points<1?'disabled':''}>+</button></div>`).join('')}</div><dl class="derived"><dt>Daño físico</dt><dd>${p.derived.damage}</dd><dt>Defensa</dt><dd>${p.derived.defense}</dd><dt>Vida máxima</dt><dd>${p.derived.maxHP}</dd><dt>Maná máximo</dt><dd>${p.derived.maxMana}</dd></dl><p class="hint">Cada nivel concede ${this.content.balance.pointsPerLevel} puntos. El servidor calcula tus atributos.</p>`;}
    else if(this.panel==='map'){html+=`<canvas id="large-map" width="280" height="340"></canvas><p class="hint">◆ Tú · ◇ NPC · círculos: spots · Aurelia: área segura</p><div class="map-legend"><p>01 · Claro del brote <b>Sproutling</b></p><p>02 · Linde de los lobos <b>Forest Wolf</b></p></div>`;}
    else if(this.panel==='help'){html+=`<div class="help-content"><p><b>Clic en suelo</b> Caminar. Un nuevo clic cambia la ruta.</p><p><b>Clic en criatura</b> Seleccionar, acercarse y atacar.</p><p><b>1 / 2 / 3</b> Ataque / Hendidura / Arco de acero.</p><p><b>Clic derecho en criatura</b> Usar la skill seleccionada; Hendidura si estaba en ataque normal.</p><p><b>Q / W</b> Poción de salud / maná.</p><p><b>Espacio</b> Recoger el botín más cercano. También puedes hacer clic en su etiqueta.</p><p><b>I / C / M</b> Inventario / personaje / mapa.</p><p><b>Rueda</b> Zoom controlado. <b>Esc</b> Detenerse y cerrar.</p><p><b>Brom</b> Espadas y reparación. <b>Lyra</b> Pociones.</p><p class="hint">El botín pertenece al vencedor durante ${this.content.balance.lootOwnership} segundos. En Aurelia recuperas vida y maná.</p></div>`;}
    else if(this.panel==='account'){html+=`<p class="hint">Tu personaje se guarda en el servidor. Registra la cuenta para volver desde otro navegador.</p><form id="account-form"><label>Nombre de cuenta<input name="username" autocomplete="username" required minlength="3" maxlength="24"></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required minlength="8" maxlength="100"></label><div class="row"><button name="register" type="submit">Registrar</button><button name="login" type="submit">Ingresar</button></div></form><p id="account-result" role="status"></p><button id="admin-button">Editor de contenido</button><p class="hint">Goal 0 · mundo original · sesión local de prototipo</p>`;}
    el.innerHTML=html;el.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{this.panel=null;el.hidden=true;};
    el.querySelectorAll<HTMLButtonElement>('[data-stat]').forEach(b=>b.onclick=()=>this.send({type:'stat',stat:b.dataset.stat as keyof Stats}));
    el.querySelectorAll<HTMLButtonElement>('[data-unequip]').forEach(b=>b.ondblclick=()=>this.send({type:'unequip',slot:b.dataset.unequip as 'weapon'|'chest'|'boots'}));
    el.querySelectorAll<HTMLButtonElement>('[data-uid]').forEach(b=>{b.ondblclick=()=>{const i=p!.inventory.find(i=>i.uid===b.dataset.uid)!;const d=this.content.items.find(d=>d.id===i.item)!;if(d.type==='consumable')this.send({type:'use',item:d.id});else this.send({type:'equip',uid:i.uid});};b.ondragstart=e=>{e.dataTransfer?.setData('text/plain',b.dataset.uid!);e.dataTransfer!.effectAllowed='move';};});
    const bag=el.querySelector<HTMLElement>('#bag-grid');if(bag){bag.ondragover=e=>e.preventDefault();bag.ondrop=e=>{e.preventDefault();const rect=bag.getBoundingClientRect(),uid=e.dataTransfer?.getData('text/plain');if(uid)this.send({type:'bag',uid,x:Math.floor((e.clientX-rect.left)/34),y:Math.floor((e.clientY-rect.top)/34)});};}
    const bigMap=el.querySelector<HTMLCanvasElement>('#large-map');if(bigMap)this.drawMap(bigMap);
    const adminButton=el.querySelector<HTMLButtonElement>('#admin-button');if(adminButton)adminButton.onclick=()=>this.adminOpen();
    const form=el.querySelector<HTMLFormElement>('#account-form');if(form)form.onsubmit=async e=>{e.preventDefault();const data=new FormData(form),mode=(e as SubmitEvent).submitter?.getAttribute('name')??'register';const response=await fetch(`/api/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:data.get('username'),password:data.get('password')})});const result=await response.json();el.querySelector('#account-result')!.textContent=response.ok?mode==='register'?'Cuenta registrada.':'Ingresando…':result.error;if(response.ok&&mode==='login')location.reload();};
  }
  renderShop(p:PlayerState){const npc=this.content.npcs.find(n=>n.id===p.npc),hash=JSON.stringify([p.npc,p.crowns,p.equipment]);if(hash===this.npcHash)return;this.npcHash=hash;this.shopEl.hidden=!npc;if(!npc)return;
    const cost=Math.ceil(Object.values(p.equipment).reduce((sum,i)=>sum+Math.max(0,(this.content.items.find(d=>d.id===i.item)?.durability??0)-i.durability)*0.3,0));
    this.shopEl.innerHTML=this.header(`${esc(npc.name)} · ${esc(npc.role)}`)+`<p class="dialogue">${esc(npc.dialogue)}</p><div class="shop-items">${npc.interaction==='shop'?[...npc.shop].sort((a,b)=>a.order-b.order).map(row=>{const item=this.content.items.find(i=>i.id===row.item)!;return`<button data-buy="${esc(item.id)}" ${p.crowns<row.price?'disabled':''}>${icon(item.icon)}<span>${esc(item.name)}<small>${esc(row.category)}</small></span><b>${row.price} C</b></button>`;}).join(''):''}</div>${npc.services.includes('repair')||npc.interaction==='repair'?`<button id="repair-button" ${p.crowns<cost?'disabled':''}>Reparar equipo · ${cost} Crowns</button>`:''}${npc.interaction!=='shop'&&npc.interaction!=='repair'?'<p class="hint">Interacción reservada para una futura expansión.</p>':''}<p class="hint">${Math.floor(p.crowns)} Crowns disponibles</p>`;
    this.shopEl.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{this.send({type:'stop'});this.shopEl.hidden=true;};
    this.shopEl.querySelectorAll<HTMLButtonElement>('[data-buy]').forEach(b=>b.onclick=()=>this.send({type:'buy',npc:npc.id,item:b.dataset.buy!}));const repair=this.shopEl.querySelector<HTMLButtonElement>('#repair-button');if(repair)repair.onclick=()=>this.send({type:'repair',npc:npc.id});
  }
  drawMap(canvas:HTMLCanvasElement){const ctx=canvas.getContext('2d')!,w=canvas.width,h=canvas.height,b=this.content.world.bounds,safe=this.content.world.safeZone;const x=(n:number)=>(n-b.minX)/(b.maxX-b.minX)*w,z=(n:number)=>(n-b.minZ)/(b.maxZ-b.minZ)*h;
    ctx.fillStyle='#29362c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#77785a';ctx.lineWidth=w/32;ctx.beginPath();ctx.moveTo(x(0),z(17));ctx.lineTo(x(0),z(4));ctx.lineTo(x(-4),z(-2));ctx.lineTo(x(8),z(-18));ctx.stroke();ctx.fillStyle='#777664';ctx.fillRect(x(safe.minX),z(safe.minZ),x(safe.maxX)-x(safe.minX),z(safe.maxZ)-z(safe.minZ));
    for(const l of this.content.world.landmarks){ctx.fillStyle=l.style==='crystal'?'#91c2ae':'#393d32';ctx.fillRect(x(l.x-l.width/2),z(l.z-l.depth/2),l.width/(b.maxX-b.minX)*w,l.depth/(b.maxZ-b.minZ)*h);}
    for(const spot of this.content.spots.filter(s=>s.enabled)){ctx.strokeStyle=spot.monster==='sproutling'?'#c0bf74':'#b87e59';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x(spot.x),z(spot.z),spot.radius/(b.maxX-b.minX)*w,spot.radius/(b.maxZ-b.minZ)*h,0,0,Math.PI*2);ctx.stroke();}
    for(const m of this.state?.monsters??[]){if(m.hp<=0)continue;ctx.fillStyle='#c89365';ctx.fillRect(x(m.x)-1,z(m.z)-1,2,2);}
    for(const npc of this.content.npcs.filter(n=>n.enabled)){ctx.fillStyle='#f0dba0';ctx.fillRect(x(npc.x)-2,z(npc.z)-2,4,4);}
    const p=this.state?.me;if(p){ctx.save();ctx.translate(x(p.x),z(p.z));ctx.rotate(-p.facing);ctx.fillStyle='#b5f2de';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(3,3);ctx.lineTo(0,1);ctx.lineTo(-3,3);ctx.closePath();ctx.fill();ctx.restore();}
    if(w>200){ctx.fillStyle='#eee2b4';ctx.font='12px Georgia';ctx.fillText('AURELIA',x(-5),z(27));ctx.fillText('GREENFIELDS',x(-20),z(-27));}
  }
  performance(scene:GameScene){this.root.querySelector('#performance')!.textContent=`${scene.fps.toFixed(0)} fps · ${scene.drawCalls} draws · ${(scene.triangles/1000).toFixed(0)}k triangles · server 30Hz / network 15Hz · zoom ${scene.view.toFixed(1)}`;}
}
